//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Pr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум рез пост.
    /// </summary>
    // *** Start programmer edit section *** (ДокумРезПост CustomAttributes)

    // *** End programmer edit section *** (ДокумРезПост CustomAttributes)
    [AutoAltered()]
    [Caption("Документ результатов поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумРезПостE", new string[] {
            "Дата as \'Дата\'",
            "ДокумРаспр as \'Документа распределения\'",
            "ДокумРаспр.ДокумПоставки.Клиенты.Заказчик as \'Заказчик\'",
            "ДокумРаспр.ДокумПоставки.Клиенты.Телефон as \'Телефон\'",
            "ДокумРаспр.ДокумПоставки.Клиенты.АдресПоставки as \'Адрес поставки\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличиеДеф as \'Наличие дефектов\'",
            "УдовлКл as \'Удовлетворенность клиента\'"})]
    [MasterViewDefineAttribute("ДокумРезПостE", "ДокумРаспр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерДокРаспр")]
    [View("ДокумРезПостL", new string[] {
            "Дата as \'Дата\'",
            "ДокумРаспр.НомерДокРаспр as \'Номер документа распределения\'",
            "СтатусЗаказа as \'Статус заказа\'",
            "НаличиеДеф as \'Наличие дефектов\'",
            "УдовлКл as \'Удовлетворенность клиента\'"})]
    public class ДокумРезПост : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Pr.СостоянЗаказа fСтатусЗаказа;
        
        private bool fНаличиеДеф;
        
        private IIS.Pr.УдКл fУдовлКл;
        
        private IIS.Pr.ДокумРаспр fДокумРаспр;
        
        // *** Start programmer edit section *** (ДокумРезПост CustomMembers)

        // *** End programmer edit section *** (ДокумРезПост CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРезПост.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумРезПост.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРезПост.Дата Get start)

                // *** End programmer edit section *** (ДокумРезПост.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумРезПост.Дата Get end)

                // *** End programmer edit section *** (ДокумРезПост.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРезПост.Дата Set start)

                // *** End programmer edit section *** (ДокумРезПост.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумРезПост.Дата Set end)

                // *** End programmer edit section *** (ДокумРезПост.Дата Set end)
            }
        }
        
        /// <summary>
        /// НаличиеДеф.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРезПост.НаличиеДеф CustomAttributes)

        // *** End programmer edit section *** (ДокумРезПост.НаличиеДеф CustomAttributes)
        public virtual bool НаличиеДеф
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРезПост.НаличиеДеф Get start)

                // *** End programmer edit section *** (ДокумРезПост.НаличиеДеф Get start)
                bool result = this.fНаличиеДеф;
                // *** Start programmer edit section *** (ДокумРезПост.НаличиеДеф Get end)

                // *** End programmer edit section *** (ДокумРезПост.НаличиеДеф Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРезПост.НаличиеДеф Set start)

                // *** End programmer edit section *** (ДокумРезПост.НаличиеДеф Set start)
                this.fНаличиеДеф = value;
                // *** Start programmer edit section *** (ДокумРезПост.НаличиеДеф Set end)

                // *** End programmer edit section *** (ДокумРезПост.НаличиеДеф Set end)
            }
        }
        
        /// <summary>
        /// СтатусЗаказа.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРезПост.СтатусЗаказа CustomAttributes)

        // *** End programmer edit section *** (ДокумРезПост.СтатусЗаказа CustomAttributes)
        public virtual IIS.Pr.СостоянЗаказа СтатусЗаказа
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРезПост.СтатусЗаказа Get start)

                // *** End programmer edit section *** (ДокумРезПост.СтатусЗаказа Get start)
                IIS.Pr.СостоянЗаказа result = this.fСтатусЗаказа;
                // *** Start programmer edit section *** (ДокумРезПост.СтатусЗаказа Get end)

                // *** End programmer edit section *** (ДокумРезПост.СтатусЗаказа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРезПост.СтатусЗаказа Set start)

                // *** End programmer edit section *** (ДокумРезПост.СтатусЗаказа Set start)
                this.fСтатусЗаказа = value;
                // *** Start programmer edit section *** (ДокумРезПост.СтатусЗаказа Set end)

                // *** End programmer edit section *** (ДокумРезПост.СтатусЗаказа Set end)
            }
        }
        
        /// <summary>
        /// УдовлКл.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРезПост.УдовлКл CustomAttributes)

        // *** End programmer edit section *** (ДокумРезПост.УдовлКл CustomAttributes)
        public virtual IIS.Pr.УдКл УдовлКл
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРезПост.УдовлКл Get start)

                // *** End programmer edit section *** (ДокумРезПост.УдовлКл Get start)
                IIS.Pr.УдКл result = this.fУдовлКл;
                // *** Start programmer edit section *** (ДокумРезПост.УдовлКл Get end)

                // *** End programmer edit section *** (ДокумРезПост.УдовлКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРезПост.УдовлКл Set start)

                // *** End programmer edit section *** (ДокумРезПост.УдовлКл Set start)
                this.fУдовлКл = value;
                // *** Start programmer edit section *** (ДокумРезПост.УдовлКл Set end)

                // *** End programmer edit section *** (ДокумРезПост.УдовлКл Set end)
            }
        }
        
        /// <summary>
        /// Докум рез пост.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРезПост.ДокумРаспр CustomAttributes)

        // *** End programmer edit section *** (ДокумРезПост.ДокумРаспр CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумРаспр"})]
        [NotNull()]
        public virtual IIS.Pr.ДокумРаспр ДокумРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРезПост.ДокумРаспр Get start)

                // *** End programmer edit section *** (ДокумРезПост.ДокумРаспр Get start)
                IIS.Pr.ДокумРаспр result = this.fДокумРаспр;
                // *** Start programmer edit section *** (ДокумРезПост.ДокумРаспр Get end)

                // *** End programmer edit section *** (ДокумРезПост.ДокумРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРезПост.ДокумРаспр Set start)

                // *** End programmer edit section *** (ДокумРезПост.ДокумРаспр Set start)
                this.fДокумРаспр = value;
                // *** Start programmer edit section *** (ДокумРезПост.ДокумРаспр Set end)

                // *** End programmer edit section *** (ДокумРезПост.ДокумРаспр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумРезПостE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРезПостE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРезПостE", typeof(IIS.Pr.ДокумРезПост));
                }
            }
            
            /// <summary>
            /// "ДокумРезПостL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРезПостL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРезПостL", typeof(IIS.Pr.ДокумРезПост));
                }
            }
        }
    }
}
