//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Pr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум поставки.
    /// </summary>
    // *** Start programmer edit section *** (ДокумПоставки CustomAttributes)

    // *** End programmer edit section *** (ДокумПоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Документ поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумПоставкиE", new string[] {
            "Дата as \'Дата\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Клиенты as \'Заказчик\'",
            "Клиенты.Заказчик as \'Заказчик\'",
            "Клиенты.Телефон as \'Телефон\'",
            "Клиенты.АдресПоставки as \'Адрес поставки\'",
            "Организация as \'Наименование организации\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Организация.Сотрудники.ФИОСотруд as \'ФИО сотрудника\'"}, Hidden=new string[] {
            "Клиенты.Заказчик",
            "Организация.НаимОрганиз"})]
    [AssociatedDetailViewAttribute("ДокумПоставкиE", "ИнфОЗаказе", "ИнфОЗаказеE", true, "", "Информация о заказе", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Заказчик")]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимОрганиз")]
    [View("ДокумПоставкиL", new string[] {
            "Дата as \'Дата\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Клиенты.Заказчик as \'Заказчик\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Организация.Сотрудники.ФИОСотруд as \'ФИО сотрудника\'"})]
    public class ДокумПоставки : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомДокПостав;
        
        private IIS.Pr.Клиенты fКлиенты;
        
        private IIS.Pr.Организация fОрганизация;
        
        private IIS.Pr.DetailArrayOfИнфОЗаказе fИнфОЗаказе;
        
        // *** Start programmer edit section *** (ДокумПоставки CustomMembers)

        // *** End programmer edit section *** (ДокумПоставки CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомДокПостав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.НомДокПостав CustomAttributes)
        public virtual int НомДокПостав
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Get start)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Get start)
                int result = this.fНомДокПостав;
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Get end)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Set start)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Set start)
                this.fНомДокПостав = value;
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Set end)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Pr.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get start)
                IIS.Pr.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Организация CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Pr.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get start)
                IIS.Pr.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)
        public virtual IIS.Pr.DetailArrayOfИнфОЗаказе ИнфОЗаказе
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)
                if ((this.fИнфОЗаказе == null))
                {
                    this.fИнфОЗаказе = new IIS.Pr.DetailArrayOfИнфОЗаказе(this);
                }
                IIS.Pr.DetailArrayOfИнфОЗаказе result = this.fИнфОЗаказе;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)
                this.fИнфОЗаказе = value;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумПоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиE", typeof(IIS.Pr.ДокумПоставки));
                }
            }
            
            /// <summary>
            /// "ДокумПоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиL", typeof(IIS.Pr.ДокумПоставки));
                }
            }
        }
    }
}
