//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Pr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум распр.
    /// </summary>
    // *** Start programmer edit section *** (ДокумРаспр CustomAttributes)

    // *** End programmer edit section *** (ДокумРаспр CustomAttributes)
    [AutoAltered()]
    [Caption("Документ распределения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумРаспрE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения\'",
            "ДокумПоставки as \'Номер документа поставки\'",
            "ДокумПоставки.НомДокПостав as \'Номер документа поставки\'",
            "ДокумПоставки.Клиенты.Заказчик as \'Заказчик\'",
            "ДокумПоставки.Клиенты.Телефон as \'Телефон\'",
            "ДокумПоставки.Клиенты.АдресПоставки as \'Адрес поставки\'",
            "ПунктПогрузки as \'Адрес пункта погрузки\'",
            "СписокБарж as \'Номер баржи\'",
            "СписокКонтей as \'Номер контейнера\'"}, Hidden=new string[] {
            "ДокумПоставки.НомДокПостав"})]
    [MasterViewDefineAttribute("ДокумРаспрE", "ДокумПоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомДокПостав")]
    [MasterViewDefineAttribute("ДокумРаспрE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ДокумРаспрE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [MasterViewDefineAttribute("ДокумРаспрE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКонтей")]
    [View("ДокумРаспрL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения\'",
            "ДокумПоставки.НомДокПостав as \'Номер документа поставки\'",
            "ПунктПогрузки.Адрес as \'Адрес погрузки\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"})]
    public class ДокумРаспр : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомерДокРаспр;
        
        private IIS.Pr.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Pr.ДокумПоставки fДокумПоставки;
        
        private IIS.Pr.СписокКонтей fСписокКонтей;
        
        private IIS.Pr.СписокБарж fСписокБарж;
        
        // *** Start programmer edit section *** (ДокумРаспр CustomMembers)

        // *** End programmer edit section *** (ДокумРаспр CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.Дата Get start)

                // *** End programmer edit section *** (ДокумРаспр.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумРаспр.Дата Get end)

                // *** End programmer edit section *** (ДокумРаспр.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.Дата Set start)

                // *** End programmer edit section *** (ДокумРаспр.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумРаспр.Дата Set end)

                // *** End programmer edit section *** (ДокумРаспр.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.НомерДокРаспр CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.НомерДокРаспр CustomAttributes)
        public virtual int НомерДокРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.НомерДокРаспр Get start)

                // *** End programmer edit section *** (ДокумРаспр.НомерДокРаспр Get start)
                int result = this.fНомерДокРаспр;
                // *** Start programmer edit section *** (ДокумРаспр.НомерДокРаспр Get end)

                // *** End programmer edit section *** (ДокумРаспр.НомерДокРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.НомерДокРаспр Set start)

                // *** End programmer edit section *** (ДокумРаспр.НомерДокРаспр Set start)
                this.fНомерДокРаспр = value;
                // *** Start programmer edit section *** (ДокумРаспр.НомерДокРаспр Set end)

                // *** End programmer edit section *** (ДокумРаспр.НомерДокРаспр Set end)
            }
        }
        
        /// <summary>
        /// Докум распр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.ДокумПоставки CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.ДокумПоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПоставки"})]
        [NotNull()]
        public virtual IIS.Pr.ДокумПоставки ДокумПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.ДокумПоставки Get start)

                // *** End programmer edit section *** (ДокумРаспр.ДокумПоставки Get start)
                IIS.Pr.ДокумПоставки result = this.fДокумПоставки;
                // *** Start programmer edit section *** (ДокумРаспр.ДокумПоставки Get end)

                // *** End programmer edit section *** (ДокумРаспр.ДокумПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.ДокумПоставки Set start)

                // *** End programmer edit section *** (ДокумРаспр.ДокумПоставки Set start)
                this.fДокумПоставки = value;
                // *** Start programmer edit section *** (ДокумРаспр.ДокумПоставки Set end)

                // *** End programmer edit section *** (ДокумРаспр.ДокумПоставки Set end)
            }
        }
        
        /// <summary>
        /// Докум распр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Pr.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ДокумРаспр.ПунктПогрузки Get start)
                IIS.Pr.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ДокумРаспр.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ДокумРаспр.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ДокумРаспр.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ДокумРаспр.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ДокумРаспр.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Докум распр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Pr.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.СписокБарж Get start)

                // *** End programmer edit section *** (ДокумРаспр.СписокБарж Get start)
                IIS.Pr.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ДокумРаспр.СписокБарж Get end)

                // *** End programmer edit section *** (ДокумРаспр.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.СписокБарж Set start)

                // *** End programmer edit section *** (ДокумРаспр.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ДокумРаспр.СписокБарж Set end)

                // *** End programmer edit section *** (ДокумРаспр.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Докум распр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРаспр.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ДокумРаспр.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Pr.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРаспр.СписокКонтей Get start)

                // *** End programmer edit section *** (ДокумРаспр.СписокКонтей Get start)
                IIS.Pr.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ДокумРаспр.СписокКонтей Get end)

                // *** End programmer edit section *** (ДокумРаспр.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРаспр.СписокКонтей Set start)

                // *** End programmer edit section *** (ДокумРаспр.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ДокумРаспр.СписокКонтей Set end)

                // *** End programmer edit section *** (ДокумРаспр.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумРаспрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРаспрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРаспрE", typeof(IIS.Pr.ДокумРаспр));
                }
            }
            
            /// <summary>
            /// "ДокумРаспрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРаспрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРаспрL", typeof(IIS.Pr.ДокумРаспр));
                }
            }
        }
    }
}
